steps:
  - label: ":books: Build site"
    plugins:
      - docker#v3.0.1:
          image: "jekyll/jekyll:3.8"
          environment:
            - "BUILDKITE_ACCESS_TOKEN"
    command:
      - python3 -m venv env
      - env/bin/pip install requests
      - ". env/bin/activate; scripts/update_docs.sh"
      - tar -czf content.tar.gz content
    artifact_paths:
      - content.tar.gz
