steps:
  - label: ":books: Prep site"
    plugins:
      - docker#v3.0.1:
          image: "python:3.6"
          environment:
            - "BUILDKITE_ACCESS_TOKEN"
    command:
      - python3 -m venv env
      - env/bin/pip install requests
      - ". env/bin/activate; scripts/update_docs.sh"
      - tar -czf styled-docs.tar.gz content/docs
    artifact_paths:
      - styled-docs.tar.gz

  - label: "jekyll"
    plugins:
      - docker#v3.0.1:
          image: "matrixdotorg/matrixdotorg-build"
    command:
      # run jekyll to generate the rest of the site.
      # This will generate stuff under ./jekyll/_site.
      - ls /var/lib/gems/2.3.0
      - . /env/bin/activate
      - ./jekyll/generate.sh
      - cp -rf ./pre-generated/* jekyll/_site/
      - tar -czf jekyll-site.tar.gz jekyll/_site
    artifact_paths:
      - jekyll-site.tar.gz

  - wait

  - label: "complete"
    command:
      - buildkite-agent artifact download styled-docs.tar.gz /
      - buildkite-agent artifact download jekyll-site.tar.gz /
      - tar -xzvf styled-docs.tar.gz
      - tar -xzvf jekyll-site.tar.tz
      - cp -r jekyll/_site/{css,guides,howtos,projects} content/docs
      - tar -czf content.tar.gz content
    artifact_paths:
      - content.tar.gz
